package main

var goPackageDataExpected = map[string]*GoPackagaedata{
	// TODO is this correct behavior?
	"zarf": {
		Files:           []string{"zarf/main.go"},
		Name:            "main",
		PublicFunctions: []string{},
		PrivateFunctions: []string{
			"main",
		},
		Imports: []string{
			"context",
			"os",
			"os/signal",
			"syscall",
			"github.com/zarf-dev/zarf/src/cmd",
			"github.com/zarf-dev/zarf/src/config",
		},
	},
	"zarf/src/internal/template": {
		Files: []string{
			"zarf/src/internal/template/template.go",
			"zarf/src/internal/template/template_test.go",
		},
		Name: "template",
		PublicFunctions: []string{
			"NewObjects",
			"WithValues",
			"WithMetadata",
			"WithBuild",
			"WithConstants",
			"WithVariables",
			"WithPackage",
			"Apply",
			"ApplyToFile",
			"TestNewObjects",
			"TestObjects_WithValues",
			"TestObjects_WithMetadata",
			"TestObjects_WithBuild",
			"TestObjects_WithConstants",
			"TestObjects_WithVariables",
			"TestApply",
			"TestFuncMap_UnsafeSprigFunctionsRemoved",
			"TestApply_UnsafeSprigFunctionsRejected",
			"TestApplyToFile",
			"TestApplyToFile_Errors",
			"TestApplyToFile_InvalidTemplate",
			"TestApplyToFile_SprigFunctions",
			"TestToYAML",
			"TestMustToYAML",
			"TestToYAMLPretty",
			"TestFromYAML",
			"TestFromYAML_Errors",
			"TestFromYAMLArray",
			"TestFromYAMLArray_Errors",
			"TestToJSON",
			"TestMustToJSON",
			"TestFromJSON",
			"TestFromJSON_Errors",
			"TestFromJSONArray",
			"TestFromJSONArray_Errors",
			"TestToTOML",
			"TestFromTOML",
			"TestFromTOML_Errors",
		},
		PrivateFunctions: []string{
			"funcMap",
			"toYAML",
			"mustToYAML",
			"toYAMLPretty",
			"fromYAML",
			"fromYAMLArray",
			"toTOML",
			"fromTOML",
			"toJSON",
			"mustToJSON",
			"fromJSON",
			"fromJSONArray",
		},
		Imports: []string{

			"bytes",
			"context",
			"encoding/json",
			"fmt",
			"maps",
			"os",
			"path/filepath",
			"strings",
			"text/template",
			"time",
			"github.com/BurntSushi/toml",
			"github.com/Masterminds/sprig/v3",
			"github.com/goccy/go-yaml",
			"github.com/zarf-dev/zarf/src/api/v1alpha1",
			"github.com/zarf-dev/zarf/src/pkg/logger",
			"github.com/zarf-dev/zarf/src/pkg/value",
			"github.com/zarf-dev/zarf/src/pkg/variables",
			"testing",
			"github.com/stretchr/testify/require",
		},
	},
	"zarf/src/internal/dns": {
		Files: []string{
			"zarf/src/internal/dns/dns.go",
			"zarf/src/internal/dns/dns_test.go",
		},
		Name: "dns",
		PublicFunctions: []string{
			"IsServiceURL",
			"ParseServiceURL",
			"IsLocalhost",
			"TestServiceURL",
			"TestIsLocalHost",
		},
		PrivateFunctions: []string{
			"isRFC1918",
		},
		Imports: []string{
			"errors",
			"fmt",
			"net",
			"net/url",
			"regexp",
			"strconv",
			"strings",
			"testing",
			"github.com/stretchr/testify/require",
		},
	},
	"zarf/src/internal/api/v1alpha1": {
		Files: []string{
			"zarf/src/internal/api/v1alpha1/validate_test.go",
			"zarf/src/internal/api/v1alpha1/validate.go",
		},
		Name: "v1alpha1",
		PublicFunctions: []string{
			"TestZarfPackageValidate",
			"TestValidateManifest",
			"TestValidateReleaseName",
			"TestValidateChart",
			"TestValidateComponentActions",
			"TestValidateComponentAction",
			"ValidatePackage",
		},
		PrivateFunctions: []string{
			"validateActions",
			"hasSetVariables",
			"hasTemplating",
			"validateActionSet",
			"validateAction",
			"validateReleaseName",
			"validateChart",
			"validateManifest",
		},
		Imports: []string{
			"fmt",
			"strings",
			"testing",
			"github.com/defenseunicorns/pkg/helpers/v2",
			"github.com/stretchr/testify/require",
			"github.com/zarf-dev/zarf/src/api/v1alpha1",
			"errors",
			"k8s.io/apimachinery/pkg/util/validation",
		},
	},
	"zarf/src/internal/pkgcfg": {
		Files: []string{
			"zarf/src/internal/pkgcfg/pkgcfg_test.go",
			"zarf/src/internal/pkgcfg/pkgcfg.go",
		},
		Name: "pkgcfg",
		PublicFunctions: []string{
			"TestParseDefinition",
			"TestParseBuiltPackageDefinition",
			"TestParseDefinitionAndParseBuiltPackageAgreeOnSingleDoc",
			"TestHandlerFor",
			"TestMigrateDeprecated",
			"Parse",
			"ParseMultiDoc",
		},
		PrivateFunctions: []string{

			"decodeV1Alpha1",
			"applyV1Alpha1Migrations",
			"handlerFor",
			"apiVersionFromNode",
			"parseZarfYAMLDocs",
			"filterEmptyDocs",
			"migrateDeprecated",
			"migrateScriptsToActions",
			"migrateSetVariableToSetVariables",
			"clearSetVariables",
		},
		Imports: []string{
			"context",
			"math",
			"testing",
			"github.com/stretchr/testify/require",
			"github.com/zarf-dev/zarf/src/api/v1alpha1",
			"errors",
			"fmt",
			"slices",
			"github.com/goccy/go-yaml",
			"github.com/goccy/go-yaml/ast",
			"github.com/goccy/go-yaml/parser",
			"github.com/zarf-dev/zarf/src/pkg/logger",
		},
	},
	"zarf/src/internal/git": {
		Files: []string{
			"zarf/src/internal/git/repository.go",
			"zarf/src/internal/git/git_test.go",
		},
		Name: "git",
		PublicFunctions: []string{
			"Open",
			"Clone",
			"Path",
			"Push",
			"TestParseRef",
		},
		PrivateFunctions: []string{
			"checkoutRefAsBranch",
		},
		Imports: []string{
			"context",
			"errors",
			"fmt",
			"os",
			"path/filepath",
			"strings",
			"github.com/go-git/go-git/v5",
			"github.com/go-git/go-git/v5/config",
			"github.com/go-git/go-git/v5/plumbing",
			"github.com/go-git/go-git/v5/plumbing/object",
			"github.com/go-git/go-git/v5/plumbing/transport",
			"github.com/go-git/go-git/v5/plumbing/transport/http",
			"github.com/zarf-dev/zarf/src/pkg/logger",
			"github.com/zarf-dev/zarf/src/pkg/transform",
			"github.com/zarf-dev/zarf/src/pkg/utils",
			"testing",
			"github.com/stretchr/testify/require",
		},
	},
}

var goPackageDataExpectedWithoutTests = map[string]*GoPackagaedata{
	"zarf": {
		Files:           []string{"zarf/main.go"},
		Name:            "main",
		PublicFunctions: []string{},
		PrivateFunctions: []string{
			"main",
		},
		Imports: []string{
			"context",
			"os",
			"os/signal",
			"syscall",
			"github.com/zarf-dev/zarf/src/cmd",
			"github.com/zarf-dev/zarf/src/config",
		},
	},
	"zarf/src/internal/template": {
		Files: []string{
			"zarf/src/internal/template/template.go",
		},
		Name: "template",
		PublicFunctions: []string{
			"NewObjects",
			"WithValues",
			"WithMetadata",
			"WithBuild",
			"WithConstants",
			"WithVariables",
			"WithPackage",
			"Apply",
			"ApplyToFile",
		},
		PrivateFunctions: []string{
			"funcMap",
			"toYAML",
			"mustToYAML",
			"toYAMLPretty",
			"fromYAML",
			"fromYAMLArray",
			"toTOML",
			"fromTOML",
			"toJSON",
			"mustToJSON",
			"fromJSON",
			"fromJSONArray",
		},
		Imports: []string{

			"bytes",
			"context",
			"encoding/json",
			"fmt",
			"maps",
			"os",
			"path/filepath",
			"strings",
			"text/template",
			"time",
			"github.com/BurntSushi/toml",
			"github.com/Masterminds/sprig/v3",
			"github.com/goccy/go-yaml",
			"github.com/zarf-dev/zarf/src/api/v1alpha1",
			"github.com/zarf-dev/zarf/src/pkg/logger",
			"github.com/zarf-dev/zarf/src/pkg/value",
			"github.com/zarf-dev/zarf/src/pkg/variables",
		},
	},
	"zarf/src/internal/dns": {
		Files: []string{
			"zarf/src/internal/dns/dns.go",
		},
		Name: "dns",
		PublicFunctions: []string{
			"IsServiceURL",
			"ParseServiceURL",
			"IsLocalhost",
		},
		PrivateFunctions: []string{
			"isRFC1918",
		},
		Imports: []string{
			"errors",
			"fmt",
			"net",
			"net/url",
			"regexp",
			"strconv",
			"strings",
		},
	},
	"zarf/src/internal/api/v1alpha1": {
		Files: []string{
			"zarf/src/internal/api/v1alpha1/validate.go",
		},
		Name: "v1alpha1",
		PublicFunctions: []string{
			"ValidatePackage",
		},
		PrivateFunctions: []string{
			"validateActions",
			"hasSetVariables",
			"hasTemplating",
			"validateActionSet",
			"validateAction",
			"validateReleaseName",
			"validateChart",
			"validateManifest",
		},
		Imports: []string{
			"errors",
			"fmt",
			"strings",
			"github.com/zarf-dev/zarf/src/api/v1alpha1",
			"k8s.io/apimachinery/pkg/util/validation",
		},
	},
	"zarf/src/internal/pkgcfg": {
		Files: []string{
			"zarf/src/internal/pkgcfg/pkgcfg.go",
		},
		Name: "pkgcfg",
		PublicFunctions: []string{
			"Parse",
			"ParseMultiDoc",
		},
		PrivateFunctions: []string{
			"decodeV1Alpha1",
			"applyV1Alpha1Migrations",
			"handlerFor",
			"apiVersionFromNode",
			"parseZarfYAMLDocs",
			"filterEmptyDocs",
			"migrateDeprecated",
			"migrateScriptsToActions",
			"migrateSetVariableToSetVariables",
			"clearSetVariables",
		},
		Imports: []string{
			"context",
			"errors",
			"fmt",
			"math",
			"slices",
			"github.com/goccy/go-yaml",
			"github.com/goccy/go-yaml/ast",
			"github.com/goccy/go-yaml/parser",
			"github.com/zarf-dev/zarf/src/api/v1alpha1",
			"github.com/zarf-dev/zarf/src/pkg/logger",
		},
	},
	"zarf/src/internal/git": {
		Files: []string{
			"zarf/src/internal/git/repository.go",
		},
		Name: "git",
		PublicFunctions: []string{
			"Open",
			"Clone",
			"Path",
			"Push",
		},
		PrivateFunctions: []string{
			"checkoutRefAsBranch",
		},
		Imports: []string{
			"context",
			"errors",
			"fmt",
			"os",
			"path/filepath",
			"strings",
			"github.com/go-git/go-git/v5",
			"github.com/go-git/go-git/v5/config",
			"github.com/go-git/go-git/v5/plumbing",
			"github.com/go-git/go-git/v5/plumbing/object",
			"github.com/go-git/go-git/v5/plumbing/transport",
			"github.com/go-git/go-git/v5/plumbing/transport/http",
			"github.com/zarf-dev/zarf/src/pkg/logger",
			"github.com/zarf-dev/zarf/src/pkg/transform",
			"github.com/zarf-dev/zarf/src/pkg/utils",
		},
	},
}
