#!/bin/bash

set -e

cat << 'EOF'
// this file is generated by run_go_metadata.sh: do not edit!
package main
type GoMetadata struct {
File string `json:"file"`
Package string `json:"package"`
Imports []string `json:"imports"`
Functions []string `json:"functions"`
}
EOF

cd zarf
printf "var goMetadataExpected = []GoMetadata{\n"
#i=0
for f in $(find . -name "*.go" -type f); do
    ../go_metadata.awk ${f}
    #((++i))
    #if [ ${i} -eq 3 ]; then
    #    break
    #fi
done
printf "}\n"